language: java
install:  cd Examples && mvn install -DskipTests=true && cd ..
script:   cd Examples && mvn test && cd ..

before_install:
  - pip install --user codecov
after_success:
  - codecov

jdk:
  - oraclejdk8

notifications:
  email:
    - viruszold@mail.ru
